### ISSUE TITLE
Unify parser and writer nutexb structs

### ISSUE THREAD

**Issue by ScanMountGoat** [jam1garner/nutexb#2]
This should be doable by specifying a custom parser for the data section. If the header is a constant size, the data length is simply `file_length - header_length`. The footer contains what appears to be the data size, but Smash Ultimate doesn't rely on this for parsing based on tests that zero the size field in the header for a nutexb.
```rust
struct Nutexb {
    data: Vec<u8>,
    footer: NutexbFooter
}
```

**Comment by jam1garner** [comment]
Woah nice :0
